### ISSUE TITLE
sugar3.activity.iconify does not work

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar-toolkit-gtk3#368]
On Ubuntu 17.10 Artful the `Gtk.Window.iconify` method called by an activity during `__init__` does not result in the activity starting hidden.  Works in previous versions.  Unaffected GTK+ 3.22.11, affected GTK+ 3.22.15.

**Comment by quozl** [comment]
May be specific to the Sugar Toolkit, as it does not occur with Python GTK+ alone.

**Test case: the Sugar Hello World activity.**

Add to the [end of `__init__`](https://github.com/sugarlabs/hello-world-fork/blob/master/activity.py#L80) a call to `self.iconify()` and start the activity; result should be window not displayed.  Incorrect behaviour on Ubuntu 18.04 with GTK+ 3.22.26.

**Test case: the GTK+ Hello World application**

Add a call to `iconify()` and start; result should be window not displayed.  Correct behaviour on Ubuntu 18.04 with GTK+ 3.22.26.

```python
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

class MyWindow(Gtk.Window):

    def __init__(self):
        Gtk.Window.__init__(self, title="Hello World")

        self.button = Gtk.Button(label="Click Here")
        self.button.connect("clicked", self.on_button_clicked)
        self.add(self.button)

    def on_button_clicked(self, widget):
        print("Hello World")

win = MyWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
win.iconify()
Gtk.main()
```

**Comment by amanharitsh123** [comment]
I was going through https://github.com/sugarlabs/sugar/blob/master/src/jarabe/journal/journalactivity.py
What if we call self.iconify() before showing the window, I changed it in the journalactivity.py file.
Although it didn't fix the issue, but I am wondering if there is another file where we can make this change.
"It’s permitted to call this function before showing a window, in which case the window will be iconified before it ever appears onscreen."
I found this on Gnome Reference Guide.

**Comment by quozl** [comment]
Thanks, good try, but as you can see in the GTK+ Hello World application test case above it doesn't matter when `iconify()` is called, as long as it is called before `Gtk.main()`.

Given that the GTK+ Hello World application test case does not reproduce, the approaches to solve this problem include;

**Understand Sugar Toolkit**
* document the pattern of GTK+ calls made by an activity between the time the `Gtk.Window` is created, the `iconify()` call, and the first call to the GTK+ main loop,
* reproduce this pattern in the GTK+ Hello World application,
* find the part of the pattern that causes the problem.

**Fix GTK+**
* test each version of GTK+ between 3.22.11 and 3.22.26, to find which version regressed,
* use `git bisect` on GTK+ sources to find the commit which regressed,
* report upstream,

**Comment by quozl** [comment]
Instrumented an activity and the Toolkit and iterated through several tests.  Two _window-state-event_ occur when the `Gtk.main()` begins, the first changing the state from nothing to `Gdk.WindowState.FOCUSED | Gdk.WindowState.ICONIFIED`, and the second changing the state to just `Gtk.WindowState.FOCUSED`.  So the cause seems likely to be something that happens after the main loop begins processing events, idles, or timeouts.

A possible workaround might be to call `iconify()` again in response to the _window-state-event_.

**Comment by quozl** [comment]
Caused by upgrade of metacity from 3.24.0 to 3.25.2, git bisect shows first bad commit is [unminimize windows with initial IconicState if first known on MapRequest](https://github.com/GNOME/metacity/commit/6875256e63fbfd4500ddd27a7bf1aafc8d4c1ca3 ported from [mutter](https://gitlab.gnome.org/GNOME/mutter/commit/be5c2eb).

**Comment by quozl** [comment]
Some testing done with a possible [patch to force Journal to iconify when Metacity misbehaves](http://dev.laptop.org/~quozl/z/1gR6x0.txt) and Metacity debugging flags; `META_DEBUG=verbose` in `.sugar/default/debug`.  Result is that Journal does not cover home view, but an animated sequence of rectangles is shown by Metacity to indicate Journal is iconified.  [Logs](http://dev.laptop.org/~quozl/z/1gR6xq.txt).

**Comment by aperezbios** [comment]
Has this been tested by anyone using Top-of-Trunk Metacity? It's possible the bug (if they consider it one) has already been fixed there. The most recent release of Metacity is 3.30.1, which was released on September 9th of this year.

**Comment by aperezbios** [comment]
Also, I noticed at https://bodhi.fedoraproject.org/updates/metacity-3.30.1-1.fc29 that there is a testing build/RPM of metacity 3.30.1 for FC29.

**Comment by quozl** [comment]
Yes, I tested Metacity HEAD as of 24th November on Ubuntu 18.04 and it reproduced the bug.  Also;
* 3.25.1 does reproduce,
* 3.24.1 does not reproduce,

**Comment by quozl** [comment]
Fixed in https://github.com/GNOME/metacity/commit/074af8f87ef89b13ff326fb5d04ee424bbfd4ced

**Comment by quozl** [comment]
It's back, under certain conditions.  https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/413.
