### ISSUE TITLE
sugar3.activity.widgets.TitleEntry ignores enter key

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar-toolkit-gtk3#375]
Learners learned to use `tab` to finish editing TitleEntry, followed by clicking the activity icon to dismiss the dialog.  A slow work flow and inconsistent with journal list view.  The `enter` key is ignored.

- [x] `enter` key must finish editing,
- [ ] `enter` key should dismiss the dialog on activities that use one (most of them except Chat),
- [ ] test with or without the save-as feature,
- [ ] backport to https://github.com/sugarlabs/sugar-toolkit.

Arose from problem report https://github.com/sugarlabs/sugar/issues/771

**Comment by Pro-Panda** [comment]
@quozl I would like to work on this issue

**Comment by quozl** [comment]
https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/f3dd2c2042ad5b3fd5256838c0ec201da9402406 fixes "enter key must finish editing".

**Comment by chimosky** [comment]
@quozl while taking a look at this, it seems  `enter key should dismiss the dialog on activities that use one (most of them except Chat)` already happens, it looks like there's no way to set the save-as feature from within sugar without using gsettings.

**Comment by chimosky** [comment]
@quozl I'll be closing this as the issue no longer exists.
