### ISSUE TITLE
sugar3.activity.widgets.DescriptionItem has no cursor

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar-toolkit-gtk3#377]
Text insertion cursor or caret is missing from the DescriptionItem on Ubuntu 18.04 beta with Sugar 0.112 and git aaea86066d6dc82f0baac99d7b7aeafe3f52b3d5.

Calling `set_cursor_visible(True)` makes no change.

**Comment by Pro-Panda** [comment]
Not reproduced on Ubuntu 16.04 with Sugar 0.112

**Comment by quozl** [comment]
Yes.  Tested again using cc2357c787cb30d02e1568a2bf23dc18c367468f i;
* does not reproduce on Ubuntu 16.04 with GTK+ 3.18.9, and;
* does continue to reproduce on the current Ubuntu 18.04 beta with GTK+ 3.22.28,

so it may be a GTK+ regression, or a problem in Sugar that is only apparent with the later GTK+.

You might reproduce with either Ubuntu 18.04 beta or by upgrading GTK+.

**Comment by quozl** [comment]
Also happens in the Wireless Key Required dialog.
