### ISSUE TITLE
Test activity collaboration fails

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/sugar-toolkit-gtk3#414]
I got the following traceback in shell.logs (Ubuntu 18.04 using rdesktop)
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/jarabe/model/neighborhood.py", line 985, in __activity_updated_cb
    bundle = registry.get_bundle(properties['type'])
KeyError: 'type
```

**Comment by Aniket21mathur** [comment]
Thanks. Yes the traceback is gone as I tested with #412 . But still the collaboration for the activity do not work. I tested with both toolkit V0.112 (without telepathy port) and #412 using Ubuntu 18.04. Though there is nothing in the logs for both the cases.

**Comment by quozl** [comment]
So the traceback was caused by your work in progress.  Therefore this issue "a traceback in shell.log" can be closed.  Thanks.

**Comment by Aniket21mathur** [comment]
Thanks. Agreed.
