### ISSUE TITLE
Buddy.props.key is a quoted bytes

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar-toolkit-gtk3#433]
On https://github.com/sugarlabs/maze-activity/pull/31 we discovered that Buddy.props.key is an instance of _str_ containing quoted _bytes_; e.g. `"b'value'"`

It can be changed back to _bytes_ using _eval_, but that incurs risk of execution of data.

We need to find out why D-Bus is returning this value in this way.

**Comment by chimosky** [comment]
Fixed in d1d839b.
