### ISSUE TITLE
 File "setup.py", line 3, in <module>     from sugar3.activity import bundlebuilder ModuleNotFoundError: No module named 'sugar3'

### ISSUE THREAD

**Issue by josharsh** [sugarlabs/sugar-toolkit-gtk3#446]
File "setup.py", line 3, in <module>
    from sugar3.activity import bundlebuilder
ModuleNotFoundError: No module named 'sugar3'

**Comment by aniruddhabagal** [comment]
Hey even I'm having the same issue...
I'm not able to run the `setup.py` file.
I'm getting the error `ModuleNotFoundError: No module named 'sugar3'`
I have installed it in ubuntu-18.04 through `sudo apt install python-sugar3`
Pls help me out in this.

**Comment by quozl** [comment]
You have installed the python2 module, please try the import with python2 if you want it to work.

**Comment by aniruddhabagal** [comment]
Thank you for the help. :)
There was an error while installing. Solved it by reinstalling the whole package again.

**Comment by chimosky** [comment]
Closing as it's stale.
