### ISSUE TITLE
urllilb.request.urlopen doesn't run interactively

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/sugar-toolkit-gtk3#447]
Noticed this while looking at getiabooks activity.

**Steps to reproduce.**
* Open python interactively.
* Run [this line](https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/master/src/sugar3/network.py#L215) interactively.

@quozl

**Comment by quozl** [comment]
The line you refer to reads;
```python
    self._info = urllib.request.urlopen(self._url)
```

What string value are you using in place of `self._url`?

The line works for me;

```log
>>> import urllib.request
>>> r = urllib.request.urlopen('https://sugarlabs.org/')
>>> █
```

The line has run interactively.

The line looks fine according to the [documentation](https://docs.python.org/3/library/urllib.request.html#module-urllib.request).

**Comment by chimosky** [comment]
Earlier I was using this link 
```
http://www.archive.org/advancedsearch.php?q=%28title%3A%28a%29%20OR%20creator%3A%28a%29%29%20AND%20format%3A%28DJVU%29&fl%5B%5D=creator&fl%5B%5D=description&fl%5B%5D=format&fl%5B%5D=identifier&fl%5B%5D=language&fl%5B%5D=publisher&fl%5B%5D=subject&fl%5B%5D=title&fl%5B%5D=volume&sort%5B%5D=title&sort%5B%5D&sort%5B%5D=&rows=500&save=yes&fmt=csv&xmlsearch=Search
```

It seems just importing `urllib` and trying to access request from there doesn't work, I tried this earlier and it still returns the same result.
```
>>> import urllib
>>> urllib.request.urlopen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'urllib' has no attribute 'request'
```

This works as expected.
```
>>> import urllib.request
>>> urllib.request.urlopen
```
