### ISSUE TITLE
No icon is present for description tab in activities's toolbar

### ISSUE THREAD

**Issue by S-kus** [sugarlabs/sugar-toolkit-gtk3#465]
After opening any activity or even terminal, no icon is rendering for the description tab, not on hovering or clicking as well. As shown below:

![sec](https://user-images.githubusercontent.com/86892991/155398104-7da2c413-e58a-47ef-906f-bff63dee1ce9.png)

![third](https://user-images.githubusercontent.com/86892991/155398112-b9d7f541-4770-4b76-9c3d-364dda713bbe.png)

**Comment by quozl** [comment]
Huh?  It's not an oversight, it's a bug.  The icon is _edit-description_ and is set here;

https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/master/src/sugar3/activity/widgets.py#L250

Icon source is here;

https://github.com/sugarlabs/sugar-artwork/blob/master/icons/scalable/actions/edit-description.svg

Do you have conflicting evidence?  Thanks.

**Comment by S-kus** [comment]
> It's not an oversight, it's a bug

Thanks, I am working on it to solve the problem.

> Do you have conflicting evidence? Thanks.

No, sorry I probably misunderstood.

**Comment by quozl** [comment]
Fixed by https://github.com/sugarlabs/sugar-artwork/commit/7efad05971afc05e90048fb90d5ece75f5d9ba31
