### ISSUE TITLE
Correct Debian installation package

### ISSUE THREAD

**Issue by sincak** [sugarlabs/sugar-toolkit-gtk3#476]
Is now:
sudo apt install python3-sugar3

**Comment by chimosky** [comment]
Thanks for letting us know, fixed in bd9616e6.

**Comment by chimosky** [comment]
Thanks for your offer, we'll accept any volunteering you can provide, there are lots of things that needs fixing for sure, you can look at our issues and we always welcome contributions, being a maintainer on the other hand requires trust that has to be earned.

Looking forward to your contributions!
